/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/Table/index copy.vue')['default']
    Form: typeof import('./src/components/Form/index.vue')['default']
    'Index copy': typeof import('./src/components/Table/index copy.vue')['default']
    ListContainer: typeof import('./src/components/ListContainer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
    TableAction: typeof import('./src/components/Table/components/TableAction.vue')['default']
    TableFooter: typeof import('./src/components/Table/components/TableFooter.vue')['default']
    TableSearch: typeof import('./src/components/Table/components/TableSearch.vue')['default']
  }
}
