/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    copy: typeof import("./src/components/Table/index copy.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElDrawer: typeof import("element-plus/es")["ElDrawer"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElRadio: typeof import("element-plus/es")["ElRadio"];
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSelectV2: typeof import("element-plus/es")["ElSelectV2"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    Form: typeof import("./src/components/Form/index.vue")["default"];
    "Index copy": typeof import("./src/components/Table/index copy.vue")["default"];
    ListContainer: typeof import("./src/components/ListContainer/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SvgIcon: typeof import("./src/components/SvgIcon.vue")["default"];
    Table: typeof import("./src/components/Table/index.vue")["default"];
    TableAction: typeof import("./src/components/Table/components/TableAction.vue")["default"];
    TableFooter: typeof import("./src/components/Table/components/TableFooter.vue")["default"];
    TableSearch: typeof import("./src/components/Table/components/TableSearch.vue")["default"];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import("element-plus/es")["ElLoadingDirective"];
  }
}
